### ISSUE TITLE
导出 xml 或 rss 链接，可以导入播客客户端收听？

### ISSUE THREAD

**Issue by rtrobin** [bikekoala/zao#25]
可否考虑将音频文件格式导出，与当前播客客户端兼容，通过播客客户端可以下载收听节目？

**Comment by bikekoala** [comment]
可能不行，这是的音频都用的 HLS 流。如果你想要 mp3 文件，可以去百度网盘下:https://pan.baidu.com/s/1atWEJcmqS24j7_ge3USvsg?_at_=1669694071056#list/path=%2FEZMorning 密码: r63c ~
